version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - run: node --version
